# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "929261813ac1219e08c16c1379aceae1010f4fbb69723ac7750fc3dbd205a6c8"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2703568268e70c6b0a4f0aaed557b3410ef9bdb5998f43b81481ba580ea83d7c"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41067a11a355904f5e8751e83f4c15144fd94f6d1000f3f99dc3482eec6a9bd5"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04d49a14c822fb9fbb09e0f0931d6911623e3d2abd5d0071d298161a72ab5c6d"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Jira, Confluence, JSM and Agile from the command line"
  homepage "https://github.com/jjuanrivvera/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
  end

  # No zap stanza required

end
