# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "11ba3a97f935b9f823e3f2cbd6e87e64c2557ed849348ba339d9a29ee65d472c"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3288bbc470c4483ee9a5cab187b6c4386c93ff4475b7028ee6d5303b366cab86"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a314df4fd192f1a4b6610a07927d8d15a0a7210cdd0ce517a38ddb352d90e773"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba0f025e194c4e0eac79ceae6087a06cc8a2d230dc0875cd20ae13e6d0840462"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Jira, Confluence, JSM and Agile from the command line"
  homepage "https://github.com/jjuanrivvera/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
  end

  # No zap stanza required

end
