# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "a1f5fe2a6a0e472b720f04461d971048ad3ef78b68a6780bae2885056d81a626"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e529a222132527eea789342f6123d0790af5ebcf6b758ed6448eafed09ec707"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa0825250b310faa5a3f900ee5937507bcbaf7459e1848e5750107c3d502d9f2"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c39458ff487910d2d41c1c63d382139a1c1e1cc8610f498206aea78403a536ea"
      url "https://github.com/jjuanrivvera/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atlassian-cli"
  desc "Jira, Confluence, JSM and Agile from the command line"
  homepage "https://github.com/jjuanrivvera/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlassian"]
  end

  # No zap stanza required
end
